## Obtener requerimientos
GET http://localhost:4004/admin-req/Requirements

## Obtener requerimiento concreto
GET http://localhost:4004/admin-req/Requirements/2

### Crear requerimientos
POST http://localhost:4004/admin-req/Requirements
Content-Type: application/json

{ "ID":6,
"reqID":"3330",
 "title":"Maestro material"}
